#this function gives a data frame of the results of linear regressions on the mean, median, and median2 migration
 #dates generated using the Phenology Function with year as the predictor

#data is a data frame generated by the phenology function

#min.num is the threshold for migration size to include a stream/year

#the logical value "peak" determines whether years/streams in which the first observation = the peak should
 #be excluded (peak=F includes, peak=T excludes)

phenology.lm<-function(data,min.num=1,peak=F){
  if(peak==F){r1<-lm(mean~Lat+Year,data=data[data$num>=min.num,])
  r2<-lm(median~Lat+Year,data=data[data$num>=min.num,])
  r3<-lm(median2~Lat+Year,data=data[data$num>=min.num,])}
  if(peak==T){r1<-lm(mean~Lat+Year,data=data[data$min!=data$peak&data$num>=min.num,])
             r2<-lm(median~Lat+Year,data=data[data$min!=data$peak&data$num>=min.num,])
             r3<-lm(median2~Lat+Year,data=data[data$min!=data$peak&data$num>=min.num,])}
  result<-data.frame("mean.P"=NA,"mean.R2"=NA,"mean.coef"=NA,"median.P"=NA,"median.R2"=NA,"median.coef"=NA,
                     "median2.P"=NA,"median2.R2"=NA,"median2.coef"=NA,"n"=NA)
  result[1,1]<-round(anova(r1)[2,5],4)
  result[1,2]<-round(summary(r1)$r.squared,3)
  result[1,3]<-round(summary(r1)$coefficients[3,1],2)
  result[1,4]<-round(anova(r2)[2,5],4)
  result[1,5]<-round(summary(r2)$r.squared,3)
  result[1,6]<-round(summary(r2)$coefficients[3,1],2)
  result[1,7]<-round(anova(r3)[2,5],4)
  result[1,8]<-round(summary(r3)$r.squared,3)
  result[1,9]<-round(summary(r3)$coefficients[3,1],2)
                     
  result[1,10]<-summary(r1)$df[1]+summary(r1)$df[2]
  
  #I added this section to help me create a figure, but it isn't necessary for the most part
  #a<-lm(median~Lat,data=data[data$peak>data$min&data$num>=min.num,])
  #plot(a$residuals~na.omit(data[data$peak>data$min&data$num>=min.num,])$Year,ylab="",xlab="")
  #a<<-lm((a$residuals~na.omit(data[data$peak>data$min&data$num>=min.num,])$Year))
  return(result)
}


#This uses the day that the maximum number of fish were observed as the metric 
#and excludes any year/stream on which the peak = the first day fish were observed
#min num allows you to adjust the threshold for inclusion based on the total number of fish observed in a year/stream
peak.lm<-function(data,min.num=1){
  r1<-lm(peak~Lat+Year,data=data[data$peak>data$min&data$num>=min.num,])
  result<-data.frame("P"=NA,"R2"=NA,"coef"=NA,"n"=NA)
  result[1,1]<-round(anova(r1)[2,5],4)
  result[1,2]<-round(summary(r1)$r.squared,3)
  result[1,3]<-round(summary(r1)$coefficients[3,1],2)
  result[1,4]<-summary(r1)$df[1]+summary(r1)$df[2]
  return(result)
}